import { Geist, Geist_Mono, Orbitron, Poppins } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./Context/UserContext";
import Navbar from "./component/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-orbitron",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "STEPS Robotics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${orbitron.variable} ${poppins.variable}`}>
      <body>
        <Navbar />
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
