import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import tailwindcss from "tailwindcss";
import autoprefixer from "autoprefixer";
import { UserProvider } from "./Context/UserContext";
import { Orbitron, Poppins } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-orbitron",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "STEPS Robotics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${orbitron.variable} ${poppins.variable}`}>
      <body>
       <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
