import { Orbitron, Poppins, Oxanium } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./Context/UserContext";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-orbitron",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-poppins",
});

const oxanium = Oxanium({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-oxanium",
});

export const metadata = {
  title: "STEPS Robotics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={oxanium.className}>
      <body>
        <Navbar />
        <UserProvider>{children}</UserProvider>
        <Footer />
      </body>
    </html>
  );
}
